# Generated by Django 4.2.6 on 2024-05-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_img', models.URLField(max_length=255)),
                ('item_low_price', models.IntegerField()),
                ('item_high_price', models.IntegerField()),
                ('item_brand', models.CharField(max_length=255)),
                ('item_maker', models.CharField(max_length=255)),
                ('item_link', models.URLField(max_length=255)),
                ('item_seller', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=200)),
                ('item_cateogry_1', models.CharField(max_length=200)),
                ('item_cateogry_2', models.CharField(max_length=200)),
                ('item_cateogry_3', models.CharField(max_length=200)),
            ],
        ),
    ]
