# Generated by Django 4.2.6 on 2024-05-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0002_alter_market_item_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="item_brand",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_cateogry_1",
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_cateogry_2",
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_cateogry_3",
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_high_price",
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_img",
            field=models.URLField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_link",
            field=models.URLField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_low_price",
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_maker",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_name",
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_seller",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="market",
            name="item_type",
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
