# Generated by Django 4.2.6 on 2024-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_alter_map_facility_lat_alter_map_facility_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="facility_category1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_category2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_category3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_explain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_holiday",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_lat",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_lng",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_new_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_old_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_parking",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="facility_province",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
