# Generated by Django 4.2.6 on 2024-05-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0003_alter_map_facility_category1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docity", models.CharField(blank=True, max_length=255)),
                ("do", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("longitude", models.CharField(blank=True, max_length=255)),
                ("latitude", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
