# Generated by Django 4.2.6 on 2024-05-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "company_num",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                (
                    "special_condition",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                (
                    "join_member",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("limit", models.CharField(blank=True, max_length=225, null=True)),
                ("save_term", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "interate_type",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("interate_rate", models.FloatField(blank=True, null=True)),
                ("interate_term", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
