# Generated by Django 4.2.6 on 2024-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="product_explain",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
