# Generated by Django 4.2.6 on 2024-05-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0005_rename_interate_term_deposit_maxi_interate_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=225)),
                ("product_summary", models.CharField(max_length=225)),
                ("company_name", models.CharField(max_length=225)),
                ("average_pay", models.CharField(max_length=225)),
                ("product_explain", models.CharField(max_length=225)),
                ("join_age", models.CharField(max_length=225)),
                ("renewal_age", models.CharField(max_length=225)),
                ("deductible", models.CharField(max_length=225)),
                ("coverage_ratio", models.CharField(max_length=225)),
                ("patella_luxation", models.BooleanField()),
                ("skin_disease", models.BooleanField()),
                ("accident_wound", models.BooleanField()),
                ("admission", models.CharField(max_length=225)),
                ("liability", models.CharField(max_length=225)),
                ("surgery", models.BooleanField()),
            ],
        ),
    ]
