# Generated by Django 4.2.6 on 2024-05-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0006_insurance"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurance",
            name="funeral",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insurance",
            name="oral_disease",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
