# Generated by Django 4.2.6 on 2024-05-17 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_followings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)'), ('X', '중성')], max_length=1)),
                ('birth_date', models.DateField()),
                ('Type', models.CharField(choices=[(1, '말티즈'), (2, '푸들'), (3, '포메라니안'), (4, '시츄'), (5, '비숑프리제'), (6, '요크셔테리어'), (7, '진도견'), (8, '치와와'), (9, '스피츠'), (10, '닥스훈트'), (11, '리트리버'), (12, '기타')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
