# Generated by Django 4.2.6 on 2024-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_dog_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_img',
            field=models.ImageField(blank=True, null=True, upload_to='dog_images/'),
        ),
    ]
