# Generated by Django 4.2.6 on 2024-05-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dog_dog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
