<<<<<<< HEAD
# Generated by Django 4.2.6 on 2024-05-17 05:51
=======
# Generated by Django 4.2.6 on 2024-05-17 05:53
>>>>>>> e8d4cfaf9e88870f3ab1bf585d6cded4622d30a3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_article_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Category',
            field=models.CharField(choices=[('고민나누기', '고민나누기'), ('중고장터', '중고장터'), ('동네사람들', '동네사람들')], max_length=5),
        ),
    ]
