# Generated by Django 4.2.6 on 2024-05-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Category',
            new_name='category',
        ),
    ]
