# Generated by Django 4.2.6 on 2024-05-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="item_seller",
            field=models.CharField(max_length=255),
        ),
    ]
