# Generated by Django 4.2.6 on 2024-05-15 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0003_deposit_special_explain"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deposit",
            old_name="company_num",
            new_name="product_num",
        ),
    ]
