# Generated by Django 4.2.6 on 2024-05-15 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0004_rename_company_num_deposit_product_num"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deposit",
            old_name="interate_term",
            new_name="maxi_interate_rate",
        ),
    ]
