# Generated by Django 4.2.6 on 2024-05-17 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0007_insurance_funeral_insurance_oral_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='like_users',
            field=models.ManyToManyField(related_name='like_deposit', to=settings.AUTH_USER_MODEL),
        ),
    ]
