# Generated by Django 4.2.6 on 2024-05-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_deposit_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
