# Generated by Django 4.2.6 on 2024-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_alter_deposit_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
