# Generated by Django 4.2.6 on 2024-05-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(max_length=20)),
                ('img', models.URLField()),
                ('gender', models.CharField(max_length=1)),
                ('notice', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=50)),
                ('center_name', models.CharField(max_length=50)),
                ('center_telephone', models.CharField(max_length=20)),
                ('center_address', models.CharField(max_length=200)),
            ],
        ),
    ]
